apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: psu0beyvv-python
  janus-idp.io/tekton: psu0beyvv-python
  backstage.io/kubernetes-id: psu0beyvv-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: psu0beyvv-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
